server:
  port: 8088
  servlet:
    context-path: /sgj
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shixuntwo?autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0